'use strict';
const $=id=>document.getElementById(id);
const colors={attractions636:'#df627e',sites636:'#589641',objects529:'#d99322',unassigned:'#7168a3'};
let data, selected=null, active='all', labels=true, scale=1, tx=0, ty=0, moved=false;
const viewport=$('viewport'),world=$('world'), pointers=new Map();
function transform(){world.style.transform=`translate(${tx}px,${ty}px) scale(${scale})`;world.style.setProperty('--inverse',1/scale);world.classList.toggle('overview',scale<.35);$('zoom').textContent=`Масштаб ${Math.round(scale*100)}% · детализация до 400%`;}
function fit(){if(!data)return;scale=Math.min(viewport.clientWidth/data.width,viewport.clientHeight/data.height)*.97;tx=(viewport.clientWidth-data.width*scale)/2;ty=(viewport.clientHeight-data.height*scale)/2;transform();}
function zoom(factor,x=viewport.clientWidth/2,y=viewport.clientHeight/2){const next=Math.max(.08,Math.min(4,scale*factor));tx=x-(x-tx)*next/scale;ty=y-(y-ty)*next/scale;scale=next;transform();}
function focusPoint(point){scale=Math.max(.65,Math.min(1.1,viewport.clientWidth/900));tx=viewport.clientWidth/2-point[0]*scale;ty=viewport.clientHeight/2-point[1]*scale;transform();}
function matches(o){const query=$('search').value.trim().toLocaleLowerCase('ru');return (active==='all'||o.group===active)&&(!query||(/^\d+$/.test(query)?String(o.id)===query:o.name.toLocaleLowerCase('ru').includes(query)));}
function render(){const visible=data.objects.filter(matches);$('count').textContent=`${visible.length} из 88 объектов`;const list=$('list');list.replaceChildren();for(const o of visible){const b=document.createElement('button');b.className='object'+(selected===o.id?' selected':'');const num=document.createElement('span');num.className='num';num.style.color=colors[o.group];num.textContent=o.id;const text=document.createElement('span');text.className='name';text.textContent=o.name;const small=document.createElement('small');small.textContent=data.groups[o.group];text.append(small);b.append(num,text);b.onclick=()=>select(o.id,true);list.append(b);}if(!visible.length){const p=document.createElement('p');p.className='empty';p.textContent='Совпадений нет. Попробуйте другой запрос или сбросьте фильтр.';list.append(p);}for(const marker of $('markers').children){const o=data.objects[Number(marker.dataset.id)-1];marker.classList.toggle('muted',!labels||!matches(o));marker.classList.toggle('selected',selected===o.id);}for(const button of $('filters').children){button.classList.toggle('active',button.dataset.group===active);button.setAttribute('aria-pressed',button.dataset.group===active);}if(selected!==null&&!matches(data.objects[selected-1])){$('card').hidden=true;selected=null;$('map-label').textContent='Вся территория';}}
function select(id,focus){const o=data.objects[id-1];selected=id;$('card').hidden=false;$('card-group').textContent=data.groups[o.group];$('card-group').style.color=colors[o.group];$('card-title').textContent=`${o.id}. ${o.name}`;$('card-basis').textContent=o.basis;$('map-label').textContent=`№${o.id} · ${o.name}`;$('locations').replaceChildren();if(o.positions.length>1){o.positions.forEach((point,i)=>{const b=document.createElement('button');b.textContent=`Метка ${i+1}`;b.onclick=()=>focusPoint(point);$('locations').append(b);});}if(focus)focusPoint(o.positions[0]);render();}
$('search').addEventListener('input',()=>{if(data)render();});$('clear').onclick=()=>{active='all';$('search').value='';selected=null;$('card').hidden=true;$('map-label').textContent='Вся территория';render();fit();};$('close').onclick=()=>{selected=null;$('card').hidden=true;$('map-label').textContent='Вся территория';render();};$('plus').onclick=()=>zoom(1.35);$('minus').onclick=()=>zoom(1/1.35);$('fit').onclick=fit;$('dense').onclick=()=>{if(!data)return;scale=Math.min(viewport.clientWidth/2050,viewport.clientHeight/1660)*.9;tx=(viewport.clientWidth-2050*scale)/2-450*scale;ty=(viewport.clientHeight-1660*scale)/2-850*scale;transform();};$('toggle').onclick=()=>{labels=!labels;$('toggle').setAttribute('aria-pressed',labels);render();};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await viewport.parentElement.requestFullscreen();}catch{ $('fullscreen').textContent='Недоступно'; }};
viewport.addEventListener('wheel',e=>{e.preventDefault();const r=viewport.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);},{passive:false});
viewport.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});viewport.setPointerCapture(e.pointerId);moved=false;viewport.classList.add('dragging');});
viewport.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);if(pointers.size===2){const other=[...pointers.entries()].find(([id])=>id!==e.pointerId)[1];const before=Math.hypot(old.x-other.x,old.y-other.y);const after=Math.hypot(e.clientX-other.x,e.clientY-other.y);if(before>0){const r=viewport.getBoundingClientRect();zoom(after/before,(e.clientX+other.x)/2-r.left,(e.clientY+other.y)/2-r.top);}}else{tx+=e.clientX-old.x;ty+=e.clientY-old.y;transform();}if(Math.abs(e.clientX-old.x)+Math.abs(e.clientY-old.y)>2)moved=true;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});});
function release(e){pointers.delete(e.pointerId);if(!pointers.size)viewport.classList.remove('dragging');}viewport.addEventListener('pointerup',release);viewport.addEventListener('pointercancel',release);
viewport.addEventListener('keydown',e=>{if(e.target.closest('button'))return;if(['+','=','-','0','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();if(e.key==='+'||e.key==='=')zoom(1.35);if(e.key==='-')zoom(1/1.35);if(e.key==='0')fit();if(e.key==='ArrowLeft')tx+=60;if(e.key==='ArrowRight')tx-=60;if(e.key==='ArrowUp')ty+=60;if(e.key==='ArrowDown')ty-=60;transform();});
new ResizeObserver(()=>{if(data)fit();}).observe(viewport);
async function start(){try{const response=await fetch('data/objects.json');if(!response.ok)throw Error('Реестр не загружен');data=await response.json();for(const [group,label] of [['all','Все объекты'],...Object.entries(data.groups)]){const b=document.createElement('button');b.className='filter';b.dataset.group=group;const sw=document.createElement('span');sw.className='swatch';sw.style.background=colors[group]||'#254936';const text=document.createElement('span');text.textContent=label;const n=document.createElement('strong');n.textContent=group==='all'?88:data.objects.filter(o=>o.group===group).length;b.append(sw,text,n);b.onclick=()=>{active=active===group?'all':group;render();};$('filters').append(b);}for(const o of data.objects){o.positions.forEach((point,i)=>{const b=document.createElement('button');b.className='marker';b.dataset.id=o.id;b.dataset.occurrence=i;b.style.left=`${point[0]}px`;b.style.top=`${point[1]}px`;b.style.setProperty('--color',colors[o.group]);b.textContent=o.id;b.title=`${o.id}. ${o.name}`;b.setAttribute('aria-label',`${o.id}. ${o.name}, метка ${i+1}`);b.onclick=()=>select(o.id,false);$('markers').append(b);});}render();fit();await $('map').decode();$('loading').hidden=true;}catch(error){$('loading').textContent='Не удалось загрузить карту. Обновите страницу.';$('count').textContent='Ошибка загрузки';console.error(error);}}
start();
